---
language: ruby
sudo: false

gemfile: src/logsearch-config/Gemfile

rvm:
  - jruby-9.1.5.0

jdk:
  - oraclejdk8

before_script:
  - cd $TRAVIS_BUILD_DIR/src/logsearch-config

script:
  - bundle exec rake
notifications:
  email: false
