#!/bin/bash

if [[ -z $1 || ! -f $1 ]]; then
  echo "Usage: $0 <stub file>"
  exit 1
fi

logsearch=$(dirname $0)/src/logsearch-config

tmp1="/tmp/logstash_parser.yml"
tmp2="/tmp/elasticsearch_logs_template_config.yml"
echo -e "properties:\n  logstash_parser:\n    filters: |">$tmp1
echo -e "properties:\n  elasticsearch_config:\n    templates:\n    - <<: (( merge ))\n    - index_template: |">$tmp2
./$logsearch/bin/build >/dev/null 2>&1
cat $logsearch/target/logstash-filters-default.conf | sed s/^/\ \ \ \ \ \ / >>$tmp1
cat $logsearch/target/logs-template.json | sed s/^/\ \ \ \ \ \ \ \ / >>$tmp2
spiff m $1 $tmp1 $tmp2
rm $tmp1 $tmp2
