releases:
- (( merge ))
- name: logsearch-for-cloudfoundry
  version: latest

jobs:
- (( merge ))
- name: ingestor
  templates:
  - (( merge ))
  - {name: ingestor_cloudfoundry-firehose, release: logsearch-for-cloudfoundry}
  - {name: parser-config-lfc, release: logsearch-for-cloudfoundry}
  properties:
    cloudfoundry:
      api_endpoint: https://api.VAR_CF_DOMAIN
      firehose_client_id: firehose-to-syslog # UAA client with 'doppler.firehose' permissions
      firehose_client_secret: VAR_CF_SECRET # UAA password of client with 'doppler.firehose' permissions
      firehose_events: LogMessage # Default value. Comma seperated list of events you would like to get. Valid options are CounterEvent,Error,HttpStartStop,LogMessage,ValueMetric,ContainerMetric.
      skip_ssl_validation: true
    syslog:
      host: (( grab jobs.ls-router.networks.[0].static_ips.[0] ))
      port: 5514
    logstash_parser:
      debug: false
      elasticsearch:
        index: "logs-%{[@metadata][index]}-%{+YYYY.MM.dd}"
        index_type: "%{@type}"
      filters:
      - logsearch-for-cf: /var/vcap/packages/logsearch-config-logstash-filters/logstash-filters-default.conf
      deployment_dictionary:
      - /var/vcap/packages/logsearch-config/deployment_lookup.yml
      - /var/vcap/jobs/parser-config-lfc/config/deployment_lookup.yml
      deployment_name:
        cf: my_cf
        diego: my_cf-diego
    create-uaa-client:
      cloudfoundry:
        system_domain: (( grab jobs.create-uaa-client.properties.create-uaa-client.cloudfoundry.system_domain ))
        uaa_admin_client_id: (( grab jobs.create-uaa-client.properties.create-uaa-client.cloudfoundry.uaa_admin_client_id ))
        uaa_admin_client_secret: (( grab jobs.create-uaa-client.properties.create-uaa-client.cloudfoundry.uaa_admin_client_secret ))

- name: ls-router
  templates:
  - (( merge ))
  - {name: route_registrar, release: logsearch-for-cloudfoundry}
  properties:
    nats:
      machines: []
      password: nats_password
      port: 4222
      user: nats_user
    route_registrar:
      routes:
      - name: kibana
        registration_interval: 60s
        port: 80
        uris:
        - (( grab jobs.create-uaa-client.properties.create-uaa-client.kibana_domain ))

- name: maintenance
  templates:
  - (( merge ))
  - {name: elasticsearch-config-lfc, release: logsearch-for-cloudfoundry}
  properties:
    elasticsearch_config:
      templates:
        - shards-and-replicas: /var/vcap/jobs/elasticsearch_config/index-templates/shards-and-replicas.json
        - index-settings: /var/vcap/jobs/elasticsearch_config/index-templates/index-settings.json
        - index-mappings: /var/vcap/jobs/elasticsearch_config/index-templates/index-mappings.json
        - index-mappings-lfc: /var/vcap/jobs/elasticsearch-config-lfc/index-mappings.json
        - index-mappings-app-lfc: /var/vcap/jobs/elasticsearch-config-lfc/index-mappings-app.json
        - index-mappings-platform-lfc: /var/vcap/jobs/elasticsearch-config-lfc/index-mappings-platform.json

- name: create-uaa-client
  lifecycle: errand
  release: logsearch-for-cloudfoundry
  instances: 1
  templates:
  - {name: create-uaa-client, release: logsearch-for-cloudfoundry}
  networks:
  - name: default
  resource_pool: errand
  properties:
    create-uaa-client:
      kibana_domain: (( concat "logs." jobs.create-uaa-client.properties.create-uaa-client.cloudfoundry.system_domain )) # The Kibana dashboard domain.
      oauth2_client_id: my_kibana_client_id  # Default value. The UAA Kibana oauth2 client id. Put an existing client id or one you want the job to create. Note the client required scopes: `openid,oauth.approvals,scim.userids,cloud_controller.read`.
      oauth2_client_secret: my_kibana_client_password  # The UAA Kibana oauth2 client id's secret
      cloudfoundry:
        system_domain: VAR_CF_DOMAIN
        uaa_admin_client_id: admin  # The UAA admin client id (required scope is `uaa.admin`). The admin client is used to manage the UAA Kibana oauth2 client.
        uaa_admin_client_secret: VAR_CF_SECRET  # The UAA admin client's secret

- name: upload-kibana-objects
  lifecycle: errand
  release: logsearch-for-cloudfoundry
  instances: 1
  templates:
  - {name: upload-kibana-objects, release: logsearch-for-cloudfoundry}
  networks:
  - name: default
  resource_pool: errand
  properties:
    elasticsearch:
      host: (( grab jobs.elasticsearch_master.networks.default.static_ips.[0] ))
      port: 9200
    cloudfoundry:
      firehose_events: (( grab jobs.ingestor.properties.cloudfoundry.firehose_events ))
    kibana_objects:
      upload_predefined_kibana_objects: true # Default value. Whether to upload Kibana objects (defaults predefined in this job) or not.
      upload_data_files: []  # List of text files to put in API endpoint /_bulk

- name: kibana
  templates:
  - (( merge ))
  - {name: kibana-auth-plugin, release: logsearch-for-cloudfoundry}
  - {name: redis, release: logsearch-for-cloudfoundry}
  persistent_disk: 1024
  properties:
    kibana:
      env:
      - NODE_ENV: production
      plugins:
      - auth: /var/vcap/packages/kibana-auth-plugin/kibana-auth-plugin.zip
      source_files: [/var/vcap/jobs/kibana-auth-plugin/config/config.sh]
    kibana-auth:
      cloudfoundry:
        skip_ssl_validation: true
        api_endpoint: (( grab jobs.ingestor.properties.cloudfoundry.api_endpoint ))
        client_id: (( grab jobs.create-uaa-client.properties.create-uaa-client.oauth2_client_id ))
        client_secret: (( grab jobs.create-uaa-client.properties.create-uaa-client.oauth2_client_secret ))
        system_domain: (( grab jobs.create-uaa-client.properties.create-uaa-client.cloudfoundry.system_domain ))
        system_org: admin
      use_https: false
      session_expiration_ms: 43200000
      redis_host: (( grab jobs.kibana.networks.default.static_ips.[0] ))  # Redis host to use for auth sessions

- name: smoke-tests
  templates:
  - (( replace ))
  - { release: logsearch-for-cloudfoundry, name: smoke-tests }
  lifecycle: errand
  instances: 1
  release: logsearch-for-cloudfoundry
  resource_pool: errand
  networks:
  - name: default
  properties:
    smoke_tests:
      api: (( grab jobs.ingestor.properties.cloudfoundry.api_endpoint ))
      system_domain: (( grab jobs.create-uaa-client.properties.create-uaa-client.cloudfoundry.system_domain ))
      admin_user: admin
      admin_password: ""
      elasticsearch_master:
        host: (( grab jobs.elasticsearch_master.networks.default.static_ips.[0] ))

properties:
  elasticsearch_config:
    index_prefix: "logs-"  # Name prefix of your log indices that you use in `logstash_parser.elasticsearch.index` property set for your parser.
    app_index_prefix: "logs-app"  # Name prefix of your `app` log indices. If you don't split `app` and `platform` indices, then just set it with the value of `elasticsearch_config.index_prefix`.
    platform_index_prefix: "logs-platform"  # Name prefix of your `platform` log indices. If you don't split `app` and `platform` indices, then just set it with the value of `elasticsearch_config.index_prefix`.
