releases:
- (( merge ))
- name: logsearch-for-cloudfoundry
  version: latest

jobs:
- name: ingestor
  templates:
  - (( merge ))
  - {name: ingestor_cloudfoundry-firehose, release: logsearch-for-cloudfoundry}

- name: parser
  templates:
  - (( merge ))
  - {name: parser-config-lfc, release: logsearch-for-cloudfoundry}
  properties:
    logstash_parser:
      debug: false
      elasticsearch:
        index: "logs-%{[@metadata][index]}-%{+YYYY.MM.dd}"
        index_type: "%{@type}"
      filters:
      - logsearch-for-cf: /var/vcap/packages/logsearch-config-logstash-filters/logstash-filters-default.conf
      deployment_dictionary:
      - /var/vcap/packages/logsearch-config/deployment_lookup.yml
      - /var/vcap/jobs/parser-config-lfc/config/deployment_lookup.yml
      deployment_name:
        cf: my_cf
        diego: my_cf-diego

- name: maintenance
  templates:
  - (( merge ))
  - {name: elasticsearch-config-lfc, release: logsearch-for-cloudfoundry}
  properties:
    elasticsearch_config:
      templates:
        - shards-and-replicas: /var/vcap/jobs/elasticsearch_config/index-templates/shards-and-replicas.json
        - index-settings: /var/vcap/jobs/elasticsearch_config/index-templates/index-settings.json
        - index-mappings: /var/vcap/jobs/elasticsearch_config/index-templates/index-mappings.json
        - index-mappings-lfc: /var/vcap/jobs/elasticsearch-config-lfc/index-mappings.json
        - index-mappings-app-lfc: /var/vcap/jobs/elasticsearch-config-lfc/index-mappings-app.json
        - index-mappings-platform-lfc: /var/vcap/jobs/elasticsearch-config-lfc/index-mappings-platform.json


- name: cf-kibana
  templates:
  - { release: logsearch-for-cloudfoundry, name: cf-kibana }
  lifecycle: errand
  instances: 1
  resource_pool: errand
  networks:
  - name: default

- name: smoke-tests
  templates:
  - (( replace ))
  - { release: logsearch-for-cloudfoundry, name: smoke-tests }
  lifecycle: errand
  instances: 1
  release: logsearch-for-cloudfoundry
  resource_pool: errand
  networks:
  - name: default

- name: upload-kibana-objects
  lifecycle: errand
  release: logsearch-for-cloudfoundry
  instances: 1
  templates:
  - {name: upload-kibana-objects, release: logsearch-for-cloudfoundry}
  networks:
  - name: default
  resource_pool: errand
  properties:
    elasticsearch:
      host: (( grab jobs.elasticsearch_master.networks.default.static_ips.[0] ))
      port: 9200
    cloudfoundry:
      firehose_events: (( grab properties.cloudfoundry.firehose_events ))
    kibana_objects:
      upload_predefined_kibana_objects: true # Default value. Whether to upload Kibana objects predefined in this job or not.
      upload_data_files: []  # List of text files to put in API endpoint /_bulk

properties:
  cloudfoundry:
    api_endpoint: https://api.my_sys.cf.example
    admin_user: admin
    admin_password: admin # Passsword of the CF admin user
    firehose_client_id: firehose-to-syslog # UAA client with 'doppler.firehose' permissions
    firehose_client_secret: VAR_CF_SECRET # UAA password of client with 'doppler.firehose' permissions
    firehose_events: LogMessage  # Default value. Comma seperated list of events you would like to get. Valid options are CounterEvent,Error,HttpStartStop,LogMessage,ValueMetric,ContainerMetric.
    skip_ssl_validation: true
  cf-kibana:
    # oauth2_use_existing_client: false  # Default value. Set true to use existing UAA oauth2 client for Kibana. Note the client required scopes: `openid,oauth.approvals,scim.userids,cloud_controller.read`.
    # oauth2_client_id: kibana_oauth2_client # Default value. Set id of existing oauth2 client if you have one.
    oauth2_client_secret: my_password_for_oauth2_client_id  # Password to be used for the UAA Kibana oauth2 client
    cloudfoundry:
      apps_domain: my_apps.example.com  # The CF apps domain ( eg: apps.10.244.0.34.xip.io )
      system_domain: my_sys.cf.example
      uaa_admin_client_id: my_uaa_admin_client_id  # The UAA admin client id (required scope is `uaa.admin`). The admin client is used to manage the UAA Kibana oauth2 client.
      uaa_admin_client_secret: my_uaa_admin_client_secret  # The UAA admin client's secret
      api_security_group: my_cf_api_security_group  # CF security group with API access
    elasticsearch:
      host: (( grab jobs.elasticsearch_master.networks.default.static_ips.[0] ))
  create-uaa-client:
    cloudfoundry:
      system_domain: (( grab properties.cf-kibana.cloudfoundry.system_domain ))
      uaa_admin_client_id: (( grab properties.cf-kibana.cloudfoundry.uaa_admin_client_id ))
      uaa_admin_client_secret: (( grab properties.cf-kibana.cloudfoundry.uaa_admin_client_secret ))
  elasticsearch_config:
    index_prefix: "logs-"  # Name prefix of your log indices that you use in `logstash_parser.elasticsearch.index` property set for your parser.
    app_index_prefix: "logs-app"  # Name prefix of your `app` log indices. If you don't split `app` and `platform` indices, then just set it with the value of `elasticsearch_config.index_prefix`.
    platform_index_prefix: "logs-platform"  # Name prefix of your `platform` log indices. If you don't split `app` and `platform` indices, then just set it with the value of `elasticsearch_config.index_prefix`.
  syslog:
    host: (( grab jobs.ls-router.networks.[0].static_ips.[0] ))
    port: 5514
  smoke_tests:
    api: (( grab properties.cloudfoundry.api_endpoint ))
    system_domain: (( grab grab properties.cf-kibana.cloudfoundry.system_domain ))
    admin_user: (( grab properties.cloudfoundry.admin_user ))
    admin_password: (( grab properties.cloudfoundry.admin_password ))
    elasticsearch_master:
      host: (( grab jobs.elasticsearch_master.networks.default.static_ips.[0] ))
      port: 9200
