releases:
- (( merge ))
- name: logsearch-for-cloudfoundry
  version: latest

jobs:
- (( merge ))
- name: ingestor
  templates:
  - (( merge ))
  - {name: ingestor_cloudfoundry-firehose, release: logsearch-for-cloudfoundry}
  properties:
    cloudfoundry:
      api_endpoint: https://api.hy.den.altoros.com
      doppler_endpoint: wss://doppler.hy.den.altoros.com
      firehose_user: admin  # CF UAA username of user with 'doppler.firehose' permissions
      firehose_password: admin  # CF UAA password of user with 'doppler.firehose' permissions
      skip_ssl_validation: true
    syslog:
      host: (( grab jobs.ingestor.networks.[0].static_ips.[0] ))
      port: 5514

- name: parser
  templates:
  - (( merge ))
  - {name: parser-config-lfc, release: logsearch-for-cloudfoundry}
  properties:
    logstash_parser:
      debug: false
      elasticsearch:
        index: "logs-%{[@metadata][index]}-%{+YYYY.MM.dd}"
        index_type: "%{@type}"
      filters:
      - logsearch-for-cf: /var/vcap/packages/logsearch-config-logstash-filters/logstash-filters-default.conf
      deployment_dictionary: /var/vcap/jobs/parser-config-lfc/config/deployment_lookup.yml
      deployment_name:
        cf: cf-tiny
        diego: cf-tiny-diego

- name: maintenance
  templates:
  - (( merge ))
  - {name: elasticsearch-config-lfc, release: logsearch-for-cloudfoundry}
  properties:
    elasticsearch_config:
      templates:
      - index_template: /var/vcap/packages/logsearch-config-es-mappings/logs-template.json

- name: create-uaa-client
  lifecycle: errand
  release: logsearch-for-cloudfoundry
  instances: 1
  templates:
  - {name: create-uaa-client, release: logsearch-for-cloudfoundry}
  networks:
  - name: default
  resource_pool: errand
  properties:
    create-uaa-client:
      kibana_domain: 216.241.178.16  # The Kibana dashboard domain. Is used for redirects. (Technically, it should be set with your ls-router IP)
      oauth2_client_id: kibana_oauth2_client  # Default value. The UAA Kibana oauth2 client id. Put an existing client id or one you want the job to create. Note the client required scopes: `openid,oauth.approvals,scim.userids,cloud_controller.read`.
      oauth2_client_secret: oauth2_client_secret  # The UAA Kibana oauth2 client id's secret
      cloudfoundry:
        system_domain: hy.den.altoros.com
        uaa_admin_client_id: admin  # The UAA admin client id (required scope is `uaa.admin`). The admin client is used to manage the UAA Kibana oauth2 client.
        uaa_admin_client_secret: admin  # The UAA admin client's secret

- name: upload-kibana-objects
  lifecycle: errand
  release: logsearch-for-cloudfoundry
  instances: 1
  templates:
  - {name: upload-kibana-objects, release: logsearch-for-cloudfoundry}
  networks:
  - name: default
  resource_pool: errand
  properties:
    elasticsearch:
      host: (( grab jobs.elasticsearch_master.networks.default.static_ips.[0] ))
      port: 9200
    kibana_objects:
      upload_data_files:
        - /var/vcap/packages/logsearch-config-kibana-objects/kibana-objects-bulk-json

- name: kibana
  templates:
  - (( merge ))
  - {name: kibana-auth-plugin, release: logsearch-for-cloudfoundry}
  properties:
    kibana:
      env:
      - KIBANA_DOMAIN: (( grab jobs.create-uaa-client.properties.create-uaa-client.kibana_domain ))
      - KIBANA_OAUTH2_CLIENT_ID: (( grab jobs.create-uaa-client.properties.create-uaa-client.oauth2_client_id  ))
      - KIBANA_OAUTH2_CLIENT_SECRET: (( grab jobs.create-uaa-client.properties.create-uaa-client.oauth2_client_secret ))
      - SKIP_SSL_VALIDATION: (( grab jobs.ingestor.properties.cloudfoundry.skip_ssl_validation ))
      - CF_API_URI: (( grab jobs.ingestor.properties.cloudfoundry.api_endpoint ))
      - CF_SYSTEM_ORG: admin  # Org Managers of this org get admin access to data in Kibana
      - REDIS_HOST: 192.168.1.99  # Redis host to use for auth sessions
      - SESSION_EXPIRATION_MS: 43200000
      - NODE_ENV: production
      - USE_HTTPS: true
      plugins:
      - auth: /var/vcap/packages/kibana-auth-plugin/kibana-auth-plugin.tar.gz
