#!/bin/sh

# Check for spruce installation
which spruce > /dev/null 2>&1 || {
  echo "Aborted. Please install spruce by following https://github.com/geofffranks/spruce#installation" 1>&2
  exit 1
}

spruce merge --prune meta "$1" "$2"

