require 'erb'
require 'rake'

# Clean tasks
task :clean do
  FileUtils.mkdir_p('target')
  FileUtils.rm_rf(Dir.glob('target/*'))
end

# Build tasks
desc "Builds Logstash filters"
task :build => :clean do
  build_erb 'src/logstash-filters/default.conf.erb', 'target/logstash-filters-default.conf'
end

def build_erb(source_erb_file, target_file)
  puts "===> Building ..."
  compile_erb source_erb_file, target_file

  puts "===> Artifacts:"
  puts `find target`
end

# Test tasks
desc "Runs unit tests against filters"
task :unit, [:rspec_files] => :build do |t, args|
  args.with_defaults(:rspec_files => "$(find spec -name *_spec.rb | grep -v integration)")
  puts "===> Testing ..."
  sh %Q[ bundle exec rspec #{args[:rspec_files]} --colour ]
end

desc "Runs integration tests against filters"
task :integration, [:rspec_files] => :build do |t, args|
  args.with_defaults(:rspec_files => "$(find spec -name *_spec.rb | grep integration)")
  puts "===> Integration Testing ..."
  sh %Q[ bundle exec rspec #{args[:rspec_files]} --colour ]
end

desc "Runs YAML validation tests"
task :yaml, [:yaml_files] => :build do |t, args|
  args.with_defaults(:yaml_files => "$(find ../.. -path ../../src -prune -o -name '*.yml' -print)")
  puts "===> Validating YAML data ..."
  sh %Q[ bundle exec yaml-lint #{args[:yaml_files]} ]
end

task default: [
  :unit,
  :integration,
  :yaml
]

def unescape_embedded_doublequote(str)
  str.gsub("_eQT_", '\\\\\\\\\"')
end

def unescape_embedded_newline(str)
  str.gsub('_eLF_', '\\\\\\\\n')
end

def compile_erb(source_file, dest_file)
  if File.extname(source_file) == '.erb'
    output = ERB.new(File.read(source_file)).result(binding)
    output = unescape_embedded_doublequote(output)
    output = unescape_embedded_newline(output)
    File.write(dest_file, output)
    puts "ERB #{source_file} -> #{dest_file}"
  else
    cp source_file, dest_file
  end
end
